### ISSUE TITLE
CLI: Running install doesn't end up with mvf

### ISSUE THREAD

**Issue by jaroel** [momentumframework/momentum#9]
Hi,

I tried following along with the ['Getting Started' guide](https://momentumframework.org/docs/getting-started.html), but somehow I don't get an `mvf` binary.

```
❯ deno run -A https://deno.land/x/momentum/cli/install.ts
Check https://deno.land/x/momentum/cli/install.ts
Successfully installed mvf! Run `mvf --version` to validate.

~/Develop/radio-dj/backend took 2s 
❯ which mvf

~/Develop/radio-dj/backend 
❯ mvf --version
```

I did try bash instead of fish, just to make sure I hadn't messed up something, but no cigar.
```
bash-3.2$ deno run -A https://deno.land/x/momentum/cli/install.ts
Check https://deno.land/x/momentum/cli/install.ts
Successfully installed mvf! Run `mvf --version` to validate.
bash-3.2$ mvf --version
bash: mvf: command not found
```

Deno version stuff:
```
deno --version 
deno 1.10.3 (release, aarch64-apple-darwin)
v8 9.1.269.27
typescript 4.2.2
```

It looked like I needed to run Deno with `--unstable`, but then it also breaks.

```
deno run -A -L debug https://deno.land/x/momentum/cli/main.ts
```

```
DEBUG RS - deno::program_state:264 - Compilation statistics:
  Files: 256
  Nodes: 115856
  Identifiers: 38286
  Symbols: 30844
  Types: 13153
  Instantiations: 17463
  Parse time: 245
  Bind time: 119
  Check time: 845
  Emit time: 530
  Total TS time: 1739
  Compile time: 1764

error: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.97.0/fs/copy.ts:96:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.97.0/fs/copy.ts:111:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.97.0/fs/copy.ts:135:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.97.0/fs/copy.ts:160:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.97.0/fs/copy.ts:183:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.97.0/fs/copy.ts:214:10

Found 6 errors.
```

Enabling '--unstable' didn't help that much either.

```
deno run -A -L debug --unstable https://deno.land/x/momentum/cli/main.ts
```

```DEBUG RS - deno::specifier_handler:401 - set_tsbuildinfo - filename "https/deno.land/ff4080c545af1b2c17b606a9ef10b9ec85ce3bf03e89c1349694e97c30286837.buildinfo"
DEBUG RS - deno::program_state:264 - Compilation statistics:
  Files: 257
  Nodes: 117909
  Identifiers: 38867
  Symbols: 31089
  Types: 13475
  Instantiations: 17976
  Parse time: 228
  Bind time: 112
  Check time: 813
  Emit time: 0
  Total TS time: 1153
  Compile time: 1170

DEBUG RS - deno_runtime::permissions:40 - ⚠️️  Granted read access to <exec_path>
DEBUG RS - deno_runtime::permissions:40 - ⚠️️  Granted env access to all
DEBUG RS - deno_runtime::permissions:40 - ⚠️️  Granted read access to <exec_path>
error: Uncaught TypeError: Cannot read property 'getMvInstallationPaths' of undefined
      .getMvInstallationPaths();
       ^
    at ToolManagerService.getToolConfigs (https://deno.land/x/momentum@v0.8.1/cli/commands/tool/tool-manager.service.ts:19:8)
    at ToolManagerService.createToolCommands (https://deno.land/x/momentum@v0.8.1/cli/commands/tool/tool-manager.service.ts:62:36)
    at Object.useFactory [as factory] (https://deno.land/x/momentum@v0.8.1/cli/commands/commands.module.ts:43:41)
    at DependencyResolver.buildFactoryNode (https://deno.land/x/momentum@v0.8.1/di/dependency-resolver.ts:109:35)
    at async resolveFunc (https://deno.land/x/momentum@v0.8.1/di/dependency-resolver.ts:56:20)
    at async DependencyResolver.resolveDependency (https://deno.land/x/momentum@v0.8.1/di/dependency-resolver.ts:68:12)
    at async DependencyResolver.buildTypeNode (https://deno.land/x/momentum@v0.8.1/di/dependency-resolver.ts:78:9)
    at async resolveFunc (https://deno.land/x/momentum@v0.8.1/di/dependency-resolver.ts:54:20)
    at async DependencyResolver.resolveDependency (https://deno.land/x/momentum@v0.8.1/di/dependency-resolver.ts:68:12)
    at async DependencyResolver.resolve (https://deno.land/x/momentum@v0.8.1/di/dependency-resolver.ts:33:13)
```

Hope this helps!

**Comment by jaroel** [comment]
Somehow Deno's bin directory isn't added to the path when installed with home-brew.
`set -x PATH /Users/roel/.deno/bin $PATH` added it and now `mvf` is found.
The other issues seem to have been resolved over time too.
